USE WAREHOUSE LIZARD_WH;
USE DATABASE DASAUTO;
USE SCHEMA DASAUTO;

SELECT * FROM DASAUTO.fact_vehicle_ownership LIMIT 10;
DESCRIBE TABLE DASAUTO.fact_vehicle_ownership;

SELECT * FROM DASAUTO.fact_vehicle_ownership LIMIT 10;

SELECT COUNT(TOTAL_VEHICLES_GLOBAL) AS TOTAL_VEHICLES_IN_DATABASE
FROM fact_vehicle_ownership;